{% if @('app.build') == 'static' %}
FROM {{ @('docker.repository') ~ '/console:' ~ @('app.version') }} as console
{% endif %}

FROM {{ @('services.nginx.base_image') }}
COPY root /

{% if @('app.build') == 'static' %}
{% for copy_directory in @('nginx.copy_directories')|filter(v => v is not empty) %}
COPY --from=console {{ copy_directory }} {{ copy_directory }}
{% endfor %}
{% else %}
VOLUME /app
{% endif %}

ENTRYPOINT ["sh", "/docker-entrypoint.d/config_render.sh"]
CMD ["nginx", "-g", "daemon off;"]
